name: sc_autoencoder
channels:
    - defaults
    - conda-forge
dependencies:
    - defaults::cudatoolkit=11.0.221
    - defaults::python=3.8.2
    - conda-forge::rich=9.10.0
    - conda-forge::mlflow=1.13.1
    - conda-forge::tensorboardx=2.1
    - seaborn
    - scikit-learn
    - statsmodels
    - numba
    - pytables
    - conda-forge::python-igraph=0.8.3
    - conda-forge::leidenalg=0.8.3
    - conda-forge::umap-learn=0.4.6
    - matplotlib
    - pandas
    - pip
    - pip:
          - tensorflow==2.4.1 # not yet on Conda with full GPU support
          - tensorflow_datasets==4.2.0
          - pycuda==2019.1.2 # not on Conda
          - system-intelligence==2.0.2 # not yet on Conda
          - scanpy==1.6.0
